gerenciamento_tarefas/urls.py
from django.contrib import admin
from django.urls import path
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('usuario/', views.usuario),
    path('usuario/submit', views.usuario_submit),
    path('tarefa/', views.tarefa),
    path('tarefa/submit', views.tarefa_submit),
    path('gerenciamento/', views.gerenciamento),
    path('mudar_status/<int:tarefa_id>/', views.mudar_status_tarefa),
    path('excluir_tarefa/<int:tarefa_id>/', views.excluir_tarefa),
]

core/models.py
from django.db import models

class Usuario(models.Model):
    nome = models.CharField (max_length=100)
    email = models.EmailField (max_length=100)
    
    def __str__(self) -> str:
        return self.nome

class Tarefa(models.Model):
    PRIORIDADE_CHOICES = [
        ('baixa', 'Baixa'),
        ('media', 'Média'),
        ('alta', 'Alta'),
    ]

    STATUS_CHOICES = [
        ('a_fazer', 'A Fazer'),
        ('fazendo', 'Fazendo'),
        ('pronto', 'Pronto'),
    ]

    usuario = models.ForeignKey (Usuario, on_delete=models.CASCADE)
    descricao = models.CharField (max_length=100)
    setor = models.CharField (max_length=100)
    prioridade = models.CharField(
        max_length=10,
        choices=PRIORIDADE_CHOICES,
        default='media',
    )
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='a_fazer',
    )
    data_cadastro= models.DateTimeField(auto_now = True)

    def __str__(self) -> str:
        return self.descricao

core/views.py
from django.shortcuts import render,redirect
from core.models import Usuario,Tarefa
from django.contrib import messages

def index (request):
    return redirect('/gerenciamento/')

def usuario (request):
    id_usuario=request.GET.get('id')
    dados={}
    if id_usuario:
        dados['usuario'] = Usuario.objects.get(id=id_usuario)
    return render(request, 'usuario.html',dados)

def usuario_submit (request):
    if request.POST:
        id_usuario = request.POST.get('id_equipamento') 
        nome = request.POST.get('nome')
        email = request.POST.get('email')
        if id_usuario:
            usuario = Usuario.objects.get(id = id_usuario)
            usuario.nome=nome
            usuario.email=email
            usuario.save()
            messages.success(request,"Usuário salvo com sucesso!")
        else:        
            Usuario.objects.create(nome=nome,
                              email=email)
            messages.success(request,"Usuário salvo com sucesso!")
    else:
        messages.success(request,"Erro ao cadastrar usuário!")
    return redirect('/usuario/')


def tarefa (request):
    id_tarefa=request.GET.get('id')
    usuarios=Usuario.objects.all()
    prioridades = dict(Tarefa.PRIORIDADE_CHOICES)
    dados={}
    if id_tarefa:
        dados['tarefa'] = Tarefa.objects.get(id=id_tarefa)
    dados['usuarios']=usuarios
    dados['prioridades']=prioridades
    return render(request, 'tarefa.html',dados)

def tarefa_submit (request):
    if request.POST:
        id_tarefa = request.POST.get('id_tarefa')
        descricao = request.POST.get('descricao')
        setor = request.POST.get('setor')
        id_usuario = request.POST.get('usuario')
        usuario = Usuario.objects.get(id = id_usuario)
        prioridade = request.POST.get('prioridade')
        status='a_fazer'
        if id_tarefa:
            tarefa = Tarefa.objects.get(id = id_tarefa)
            tarefa.descricao=descricao
            tarefa.setor=setor
            tarefa.usuario=usuario
            tarefa.prioridade=prioridade
            if tarefa.status=="":
                tarefa.status=status='a_fazer'
            tarefa.save()
            messages.success(request,"Tarefa salva com sucesso!")
        else:        
            Tarefa.objects.create(descricao=descricao,
                              setor=setor,
                              usuario=usuario,
                              prioridade=prioridade,
                              status=status)
            messages.success(request,"Tarefa salva com sucesso!")
    else:
        messages.success(request,"Erro ao cadastrar tarefa!")
    return redirect('/tarefa/')


def gerenciamento(request):
    tarefas = Tarefa.objects.all()
    
    tarefas_a_fazer = tarefas.filter(status='a_fazer')
    tarefas_fazendo = tarefas.filter(status='fazendo')
    tarefas_feito = tarefas.filter(status='pronto')
    
    prioridades = dict(Tarefa.PRIORIDADE_CHOICES)
    statusList = dict(Tarefa.STATUS_CHOICES)
    
    return render(request, 'gerenciamento.html', {
        'tarefas_a_fazer': tarefas_a_fazer,
        'tarefas_fazendo': tarefas_fazendo,
        'tarefas_feito': tarefas_feito,
        'prioridades': prioridades,
        'statusList':statusList,
    })

def mudar_status_tarefa(request, tarefa_id):
    if request.POST:
        tarefa = Tarefa.objects.get(id=tarefa_id)
        status = request.POST.get('status')

        tarefa.status = status
        tarefa.save()
        messages.success(request, 'Status da tarefa atualizado com sucesso.')
    else:
        messages.error(request, 'Tarefa não encontrada.')
    
    return redirect('/gerenciamento/')  # Redireciona para a página de gerenciamento

def excluir_tarefa(request, tarefa_id):
    try:
        tarefa = Tarefa.objects.get(id=tarefa_id)
        tarefa.delete()
        messages.success(request, 'Tarefa excluída com sucesso.')
    except Tarefa.DoesNotExist:
        messages.error(request, 'Tarefa não encontrada.')
    
    return redirect('/gerenciamento/')  # Redireciona para a página de gerenciamento

core/templates/gerenciamento.html
{% extends "model-page.html" %}
{% block content %}
<div class="kanban-container">
    <div class="kanban-column" id="a-fazer">
        <h2>A Fazer</h2>
        {% for tarefa in tarefas_a_fazer %}
        <div class="kanban-card">
            <h3>{{ tarefa.descricao }}</h3>
            <p><strong>Setor:</strong> {{ tarefa.setor }}</p>
            <p><strong>Prioridade:</strong> {{ tarefa.get_prioridade_display }}</p>
            <p><strong>Vinculado a:</strong> {{ tarefa.usuario.nome }}</p>
            <div class="kanban-buttons">
                <a href="/tarefa/?id={{tarefa.id}}">
                    <button type="button">Editar</button>
                </a>
                <a href="/excluir_tarefa/{{tarefa.id}}/">
                    <button type="button">Excluir</button>
                </a>
                <!-- Formulário para alteração de status -->
                <form action="/mudar_status/{{tarefa.id }}/" method="POST">
                    {% csrf_token %}
                    <select id="status" name="status" required onchange="this.form.submit()">
                        <option value="{{ tarefa.status }}">{{ tarefa.get_status_display }}</option>
                        {% for key, status in statusList.items %}
                            <option value="{{ key }}">{{ status }}</option>
                        {% endfor %}
                    </select>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="kanban-column" id="fazendo">
        <h2>Fazendo</h2>
        {% for tarefa in tarefas_fazendo %}
        <div class="kanban-card">
            <h3>{{ tarefa.descricao }}</h3>
            <p><strong>Setor:</strong> {{ tarefa.setor }}</p>
            <p><strong>Prioridade:</strong> {{ tarefa.get_prioridade_display }}</p>
            <p><strong>Vinculado a:</strong> {{ tarefa.usuario.nome }}</p>
            <div class="kanban-buttons">
                <a href="/tarefa/?id={{tarefa.id}}">
                    <button type="button">Editar</button>
                </a>
                <a href="/excluir_tarefa/{{tarefa.id}}/">
                    <button type="button">Excluir</button>
                </a>
                <!-- Formulário para alteração de status -->
                <form action="/mudar_status/{{tarefa.id }}/" method="POST">
                    {% csrf_token %}
                    <select id="status" name="status" required onchange="this.form.submit()">
                        <option value="{{ tarefa.status }}">{{ tarefa.get_status_display }}</option>
                        {% for key, status in statusList.items %}
                            <option value="{{ key }}">{{ status }}</option>
                        {% endfor %}
                    </select>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="kanban-column" id="feito">
        <h2>Feito</h2>
        {% for tarefa in tarefas_feito %}
        <div class="kanban-card">
            <h3>{{ tarefa.descricao }}</h3>
            <p><strong>Setor:</strong> {{ tarefa.setor }}</p>
            <p><strong>Prioridade:</strong> {{ tarefa.get_prioridade_display }}</p>
            <p><strong>Vinculado a:</strong> {{ tarefa.usuario.nome }}</p>
            <div class="kanban-buttons">
                <a href="/tarefa/?id={{tarefa.id}}">
                    <button type="button">Editar</button>
                </a>
                <a href="/excluir_tarefa/{{tarefa.id}}/">
                    <button type="button">Excluir</button>
                </a>

                <!-- Formulário para alteração de status -->
                <form action="/mudar_status/{{tarefa.id }}/" method="POST">
                    {% csrf_token %}
                    <select id="status" name="status" required onchange="this.form.submit()">
                        <option value="{{ tarefa.status }}">{{ tarefa.get_status_display }}</option>
                        {% for key, status in statusList.items %}
                            <option value="{{ key }}">{{ status }}</option>
                        {% endfor %}
                    </select>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% if messages %}
<div>
    <ul>
        {% for message in messages %}
            <li> {{ message }}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}
<style>
    .kanban-container {
        display: flex;
        justify-content: space-between;
        padding: 20px;
    }

    .kanban-column {
        background-color: #e9ecef; /* Light gray for the column */
        border-radius: 8px;
        padding: 15px;
        width: 30%;
        min-height: 400px; /* Ensure columns have some height */
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .kanban-card {
        background-color: #ffffff; /* White for cards */
        border-radius: 5px;
        padding: 10px;
        margin-bottom: 15px;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
    }

    .kanban-buttons {
        margin-top: 10px;
    }

    button {
        background-color: #6c757d; /* Gray */
        color: #ffffff; /* White text */
        border: none;
        padding: 8px 12px;
        cursor: pointer;
        border-radius: 4px;
        font-size: 14px;
        transition: background-color 0.3s ease;
    }

    button:hover {
        background-color: #5a6268; /* Darker gray on hover */
    }

    select {
        margin-left: 10px;
        padding: 8px;
        border-radius: 4px;
        border: 1px solid #ced4da;
        font-size: 14px;
    }
</style>

{% endblock %}

core/templates/index.html
{% extends "model-page.html" %}
{% block content %}
    <div>
        <h2>Gerenciamento de Tarefas</h2>

        <div>
            <h3>Bem-vindo ao Sistema de Gestão de Tarefas</h3>

            <div>
                <h4>Ações rápidas</h4>
                <a href="/usuario/">
                    <button>Cadastro de Usuários</button>
                </a>
                <a href="/tarefa/">
                    <button>Cadastro de Tarefas</button>
                </a>
                <a href="/gerenciar/">
                    <button>Gerenciar Tarefas</button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

core/templates/model-header.html
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Gestão de tarefas</title>
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

core/templates/model-page.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    {% include "model-header.html" %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav>
        <a href="/">Gerenciamento de Tarefas</a>
        <div id="navbarNav">
            <ul>
                <li>
                    <a href="/usuario/">Cadastro de Usuários</a>
                </li>
                <li>
                    <a href="/tarefa/">Cadastro de Tarefas</a>
                </li>
                <li>
                    <a href="/gerenciamento/">Gerenciar Tarefas</a>
                </li>
            </ul>
        </div>
    </nav>
        {% block content %} {% endblock %}
    {% include "model-footer.html" %}
</body>
</html>

core/templates/tarefa.html
{% extends "model-page.html" %}
{% block content %}
    <div>
        <h2>Cadastro de Tarefas</h2>

        <form action="submit" method="POST">
            {% csrf_token %}
            <input type="number" name="id_tarefa" value="{{ tarefa.id }}" hidden>

            <label for="descricao">Descricao</label>
            <input type="text" id="descricao" name="descricao" value="{{ tarefa.descricao }}" required>

            <label for="setor">Setor</label>
            <input type="text" id="setor" name="setor" value="{{ tarefa.setor }}" required>

            <label for="usuario">Usuário</label>
            <select id="usuario" name="usuario" required>
                <option value="{{ tarefa.usuario.id }}">{{ tarefa.usuario.nome }}</option>
                {% for usuario in usuarios %}
                    <option value="{{ usuario.id }}">{{ usuario.nome }}</option>
                {% endfor %}
            </select>

            <label for="prioridade">Prioridade</label>
            <select id="prioridade" name="prioridade" required>
                <option value="" disabled {% if tarefa.id %} selected {% endif %}>Selecione a prioridade</option>
                {% for key, prioridade in prioridades.items %}
                    <option value="{{ key }}" {% if key == tarefa.prioridade %} selected {% endif %}>{{ prioridade }}</option>
                {% endfor %}
            </select>

            <div>
                <button type="submit">Salvar</button>
                <a href="/">
                    <button type="button">Cancelar</button>
                </a>
            </div>
        </form>
        
    {% if messages %}
    <div>
        <ul>
            {% for message in messages %}
                <li> {{ message }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    </div>
{% endblock %}

core/templates/usuario.html
{% extends "model-page.html" %}
{% block content %}
    <div>
        <h2>Cadastro de Usuários</h2>

        <form action="submit" method="POST">
            {% csrf_token %}
            <input type="number" name="id_usuario" value="{{ usuario.id }}" hidden>

            <label for="nome">Nome</label>
            <input type="text" id="nome" name="nome" value="{{ usuario.nome }}" required>

            <label for="email">E-mail</label>
            <input type="email" id="email" name="email" value="{{ usuario.email }}" required>

            <div>
                <button type="submit">Salvar</button>
                <a href="/">
                    <button type="button">Cancelar</button>
                </a>
            </div>
        </form>
        
    {% if messages %}
    <div>
        <ul>
            {% for message in messages %}
                <li> {{ message }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    </div>
{% endblock %}